Accept predicate in constructor for JwtIssuerAuthenticationManagerRes…
spring-projects/spring-security pull request #10002
Opened 2021-06-25 08:40 UTC by barrypitman

Add a constructor to JwtIssuerAuthenticationManagerResolver to allow it to accept a Predicate<String> to determine whether an issuer should be trusted or not. This allows for cases where the trusted issuers are not necessarily known at application startup. Since JwtIssuerAuthenticationManagerResolver is final and internal classes are private, this is not possible to extend it to support this use case without duplicating the whole class.

2021-06-25 08:40 UTC, pivotal-cla commented
@barrypitman Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=10002)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=10002) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-06-25 08:42 UTC, pivotal-cla commented
@barrypitman Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=10002)!

2021-06-28 18:19 UTC, jzheaux requested changes
Thanks, @barrypitman! I've left some feedback inline.

In addition to that feedback, will you please [format your commit message](https://github.com/spring-projects/spring-security/blob/fe99c3b83bd41dc926832d01fd4313c8e852230a/CONTRIBUTING.adoc#format-commit-messages)?

2021-06-28 18:19 UTC, jzheaux commented on oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerAuthenticationManagerResolver.java
>  				new TrustedIssuerJwtAuthenticationManagerResolver(
Will you please update the copyright message to now include `2021`?

2021-06-28 18:19 UTC, jzheaux commented on oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerAuthenticationManagerResolver.java
> +        this.authenticationManager = new ResolvingAuthenticationManager(
Please check for null constructor parameters. You can look at the other constructors as examples.

2021-06-28 18:19 UTC, jzheaux commented on oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerAuthenticationManagerResolver.java
> +     */
Please add `@since 5.6`

2021-06-28 18:19 UTC, jzheaux commented on oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerAuthenticationManagerResolver.java
> +    }
Please add unit tests in `JwtIssuerAuthenticationManagerResolverTests`.

2021-06-28 18:19 UTC, jzheaux commented on oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtIssuerAuthenticationManagerResolver.java
Are you able to add this same functionality for `JwtIssuerReactiveAuthenticationManagerResolver`?

2021-07-26 18:35 UTC, jzheaux commented
Hi, @barrypitman! Are you able to apply the requested changes?

2021-11-18 19:22 UTC, jzheaux commented
@barrypitman, thinking about this a bit more in conjunction with https://github.com/spring-projects/spring-security/pull/10476, I think that the best constructor for these use cases is `JwtIssuerAuthenticationManagerResolver(AuthenticationManagerResolver<String>)`, which already exists.

The reason is that introducing every constructor to allow for the myriad configurations applications want to do will become hard to maintain. In isolation, each seems reasonable and small, but the small changes start to add up. 

Instead, I believe we can simplify composing a custom `AuthenticationManagerResolver<String>`.

For example, an `AuthenticationManagerResolver<String>` with a custom `Predicate` would look something like this:

```java
public class MyAuthenticationManagerResolver implements AuthenticationManagerResolver<String> {
  Predicate<String> myPredicate = // ...

  @Cacheable(unless="#result==null")
  public AuthenticationManager resolve(String issuer) {
    if (!myPredicate.test(issuer)) {
      return null;
    }
    return new JwtAuthenticationProvider(JwtDecoders.fromIssuerLocation(issuer))::authenticate;
  }
}

// ...

@Bean 
AuthenticationManagerResolver<String> multitenantResolver() {
  return new JwtIssuerAuthenticationManagerResolver(new MyAuthenticationManagerResolver());
}
```

which, while already quite simple, could be further simplified by Spring Security exposing a default resolver like so:

```java
public static AuthenticationManager fromIssuerLocation(String issuer) {
  return new JwtAuthenticationProvider(JwtDecoders.fromIssuerLocation(issuer))::authenticate;
}
```

As such, I'm going to close this PR. Please let me know if I've missed something that makes it more complex than I've described, and you and I can take another look at simplifying your use case.

2021-11-18 19:22 UTC, closed without merging

2021-11-19 12:08 UTC, barrypitman commented
No problem, thanks for the explanation Josh