Introducing WebSessionServerLogoutHandler
spring-projects/spring-security pull request #10046
Opened 2021-07-05 21:16 UTC by orange-buffalo

As discussed in #8971, this PR is introducing `WebSessionServerLogoutHandler` and closes #4838.

2021-07-05 21:18 UTC, orange-buffalo commented
One open question left to finalize the implementation - should session invalidation be enabled by default? If yes, it would be consistent with Servlet implementation. Otherwise we would need to document the new handler.

2021-07-26 17:49 UTC, jzheaux reviewed
Yes, @orange-buffalo, please invalidate the session by default. The reason is that the application can simply not add this `ServerLogoutHandler` to their application if they don't want the session invalidated.

Even though it's a draft PR, I left a couple of reminders for you in prepping the PR for review.

2021-08-08 05:18 UTC, orange-buffalo commented on web/src/main/java/org/springframework/security/web/server/authentication/logout/WebSessionServerLogoutHandler.java
> + * @since 5.5
Sure, done

2021-08-08 05:18 UTC, orange-buffalo commented on web/src/main/java/org/springframework/security/web/server/authentication/logout/WebSessionServerLogoutHandler.java
> +	public Mono<Void> logout(WebFilterExchange filterExchange, Authentication authentication) {
No worries, renamed

2021-08-08 05:20 UTC, orange-buffalo commented
Thanks @jzheaux, I've enabled the handler by default and incorporated the suggested changes. PR is now ready for review.

2021-08-12 18:59 UTC, jzheaux requested changes
Thanks, @orange-buffalo! I apologize for being unclear, we shouldn't change `ServerHttpSecurity`'s default behavior. If you remove your changes from `ServerHttpSecurity` and `ServerHttpSecurityTests`, I believe we are good to go. Can you please make that change?

2021-08-14 21:57 UTC, orange-buffalo commented
No worries, reverted those changes.

2021-08-16 18:21 UTC, jzheaux approved these changes

2021-08-16 19:08 UTC, merged

2021-08-16 19:08 UTC, jzheaux commented
Thanks, @orange-buffalo! This is now merged into `main`