Fixes the Javadoc of ClaimAccessor methods for Map/List
spring-projects/spring-security pull request #10129
Opened 2021-07-20 19:31 UTC by shartte

Fixes #10117 by correcting the Javadoc to match the implementation behavior.

2021-07-20 19:31 UTC, pivotal-cla commented
@shartte Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=10129)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=10129) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-07-20 19:33 UTC, shartte commented
@pivotal-cla This is an Obvious Fix

2021-07-20 19:34 UTC, pivotal-cla commented
@shartte This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

2021-07-23 20:16 UTC, jzheaux requested changes
Thanks for the PR, @shartte! I've left some feedback inline.

Also, in preparation for merging will you please squash your commits and format them according to [the contributing guidelines](https://github.com/spring-projects/spring-security/blob/main/CONTRIBUTING.adoc#format-commit-messages)?

2021-07-23 20:16 UTC, jzheaux commented on oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/ClaimAccessor.java
> +	 * @throws IllegalArgumentException If the claim exists, but cannot be converted to a
For consistency with the rest of the Javadoc, will you please leave "If" lowercased in both of your changes?

2021-07-23 20:16 UTC, jzheaux commented on oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/ClaimAccessor.java
>  	 * Returns the claim value as a {@code Map<String, Object>} or {@code null} if it does
Please update the copyright messages to go to "2021"

2021-07-24 15:00 UTC, shartte commented
I am sorry, but this is turning out to be more busywork than I had anticipated to update two lines of javadoc.
I'll leave this for someone else.

2021-07-24 15:00 UTC, closed without merging

2021-07-27 16:12 UTC, jzheaux commented
> I am sorry, but this is turning out to be more busywork than I had anticipated

I can see how for a small change some of these guidelines may seem like a lot to do. I'm sorry if I made it seem like busywork. Holding to these contribution guidelines plays an important role in keeping the code quality high - it was not my intent to just give you meaningless work to keep you busy.

Thank you for taking the time to contribute, and I hope to see you again down the road.