#10262
spring-projects/spring-security pull request #10269
Opened 2021-09-14 20:31 UTC by bishoybasily

#10262 
A setter added to set the `BodyExtractor` inside the `AbstractWebClientReactiveOAuth2AccessTokenResponseClient`

2021-09-15 16:47 UTC, jzheaux requested changes
Thanks, @bishoybasily!

Please see my inline comments. In addition, will you please add tests that confirm this method works? I think there should be one in each `AbstractWebClientReactiveOAuth2AccessTokenResponseClient` implementation's test classes.

Once you are ready, will you please squash your commits and ensure that the commit message ends with "Closes gh-10260" like so:

```
Add setBodyExtractor

Closes gh-10260
```

2021-09-15 16:47 UTC, jzheaux commented on oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/endpoint/AbstractWebClientReactiveOAuth2AccessTokenResponseClient.java
> +		this.bodyExtractor = bodyExtractor;
Will you please add a null check here? `Assert.notNull` is handy.

2021-09-15 19:06 UTC, bishoybasily commented
Hi @jzheaux,
all done, please let me know if something else is missing

2021-09-15 21:01 UTC, jzheaux requested changes
Thanks for the quick turnaround, @bishoybasily!

In addition to my inline comments, will you please double-check that you have a successful run of

```bash
./gradlew format check
```

and make the needed changes? And finally, remember to squash your commits when you are ready.

2021-09-16 07:49 UTC, bishoybasily commented on oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/endpoint/WebClientReactiveAuthorizationCodeTokenResponseClientTests.java
> +		customClient.setBodyExtractor((inputMessage, context) -> {
replaced with a mock 👍

2021-09-16 07:51 UTC, bishoybasily commented
Hi @jzheaux 

Done!

- 1. - Impl. replaced with mock in tests
- 2. - CheckStyle errors fixed

2021-09-22 21:34 UTC, jzheaux approved these changes

2021-09-22 21:34 UTC, jzheaux commented
Thanks, @bishoybasily, this is now merged into `main` with 860690491aad0ee16ea3b49ab267995b4a30d90f

2021-09-22 21:34 UTC, closed without merging

2021-09-23 07:17 UTC, bishoybasily commented
Thanks, @jzheaux