Saml2WebSsoAuthenticationFilter adds authentication details
spring-projects/spring-security pull request #10306
Opened 2021-09-21 12:58 UTC by Kehrlann

Closes gh-7722.

2021-09-21 13:07 UTC, Kehrlann commented
Hi there!

We've been needing authentication details in our product, specifically `WebAuthenticationDetails`. I saw gh-7722 and decided to submit this.

Notes:
- I added a test in `Saml2WebSsoAuthenticationFilterTests` rather than more integration-style `Saml2LoginConfigurerTests`, but I am unsure whether it is the right place. Maybe they should be in both?
- There is a cast to `AbstractAuthenticationToken`. Technically the authentication converter returns a `Saml2AuthenticationToken` by default. Howver, that is not required. I can't really imagine a setup where a user provides both their own converter AND their own auth provider (they should probably provide their own filter if they do this), but I prefer being extra cautious. Please advise if that is too cautious.

2021-09-24 18:03 UTC, marcusdacoregio requested changes
Hi @Kehrlann, thank you very much for the PR. I've left some feedback inline.

2021-09-24 18:03 UTC, marcusdacoregio commented on saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationFilter.java
> +
Could you please extract this in a private method called `setDetails` so it becomes more readable?

2021-09-24 19:45 UTC, Kehrlann commented on saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationFilterTests.java
> +		Saml2AuthenticationRequestRepository<AbstractSaml2AuthenticationRequest> authenticationRequestRepository = mock(
Good catch 👍

2021-09-27 11:50 UTC, marcusdacoregio requested changes
Thank you @Kehrlann.

I've left a couple more suggestions in line. Once you fix them we can merge the PR!

2021-09-27 11:50 UTC, marcusdacoregio commented on saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationFilter.java
> +		this.setDetails(request, authentication);
In Spring Security's codebase, there are some places that we still call an instance method using `this`, but we are moving away from it. Would you please remove the `this.` and just use `setDetails(request, authentication)`?

2021-09-27 11:50 UTC, marcusdacoregio commented on saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationFilterTests.java
> +				Saml2AuthenticationRequestRepository.class);
I think the `authenticationRequestRepository` is not needed in this test.

2021-09-27 14:44 UTC, marcusdacoregio approved these changes

2021-09-27 14:44 UTC, merged

2021-09-27 14:44 UTC, marcusdacoregio commented
Thank you very much @Kehrlann. This is now merged into `main`.