Fixed NPE in MappedJwtClaimSetConverter
spring-projects/spring-security pull request #10549
Opened 2021-11-23 18:43 UTC by mitasov-ra

Issue #10548
Conversion is no longer called for missing claims.
Conversion is no longer called for claims with null value.

2021-11-23 18:43 UTC, pivotal-cla commented
@mitasov-ra Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=10549)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=10549) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-11-23 18:49 UTC, pivotal-cla commented
@mitasov-ra Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=10549)!

2021-11-25 16:15 UTC, eleftherias requested changes
@mitasov-ra, let's continue this discussion on the related issue gh-10549.
I will note that we would not be able to accept this PR as-is, because the suggested changes break some of the existing functionality.
We want to allow users to add new claims by providing a custom converter.
This is illustrated in the tests, specifically https://github.com/spring-projects/spring-security/blob/74e3abc992e5372a42787dfb757ca732b5459f75/oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/MappedJwtClaimSetConverterTests.java#L144-L153

The behavior is also described the Javadoc for the `MappedJwtClaimSetConverter` constructor
>  A converter that returns a non-null value **adds** or replaces that claim in the claim set.

2021-12-01 10:58 UTC, eleftherias commented
@mitasov-ra, I'm going to close this PR for this reasons mentioned in my previous comment.
I will keep the associated issue, gh-10549, open.

2021-12-01 10:58 UTC, closed without merging

2021-12-06 17:45 UTC, mitasov-ra commented
Got it, didn't spot that "adds" part in docs.