Prevent having both `FilterSecurityInterceptor` and `AuthorizationFilter`on filter chain
spring-projects/spring-security pull request #10574
Opened 2021-12-01 13:22 UTC by marcusdacoregio

Closes gh-10573

2021-12-02 14:44 UTC, marcusdacoregio commented
Thanks for the feedback @rwinch.

Totally agreed. Users who add filters manually know exactly what they are doing. I'm going to apply the changes.

2021-12-02 19:08 UTC, marcusdacoregio commented
I've updated the PR to avoid having `authorizeHttpRequests` and `authorizeRequests` in the same configuration.

2021-12-03 15:48 UTC, rwinch requested changes

2021-12-03 15:48 UTC, rwinch commented on config/src/main/java/org/springframework/security/config/annotation/web/configurers/AuthorizeHttpRequestsConfigurer.java
> +		ExpressionUrlAuthorizationConfigurer<?> configurer = http
Can we move this to where we are building http? I'd prefer the configurers not need to know about each other.

2021-12-03 16:43 UTC, marcusdacoregio commented
Thanks @rwinch. I've updated the PR.

2021-12-06 15:10 UTC, rwinch approved these changes
The code looks great!

The only other change is the PR should be pointed to 5.7 branch rather than main since the ticket is (rightfully) assigned to 5.7

2021-12-06 18:47 UTC, merged