Add OpenSamlAssertingPartyDetails
spring-projects/spring-security pull request #10794
Opened 2022-01-31 23:21 UTC by jzheaux

Closes gh-10781

2022-01-31 23:25 UTC, jzheaux commented
@OrangeDog, does this meet the use case you identified in [this comment](https://github.com/spring-projects/spring-security/issues/10551#issue-1063762053):

> `RelyingPartyRegistrations.fromMetadataLocation` only results in a single `RelyingPartyRegistration`, and the full entity descriptor does not appear to be available from that - e.g. the `<EntityAttributes>` and `<Extensions>`.

2022-02-01 10:30 UTC, OrangeDog commented
I assume it does. You guys tested it, right?

It will still need verification of the `EntitiesDescriptor` signature, especially when SSL is not available.
And ideally the ability to see and use the response's cache details, otherwise both users and the federation host get annoyed with you.

Let me go put some of my code examples on my top-level issue and you can hopefully put together an equivalent example for Spring 5/6.

2022-02-07 11:51 UTC, marcusdacoregio requested changes
Great @jzheaux. I've left some feedback inline.

2022-02-07 11:51 UTC, marcusdacoregio commented on saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/OpenSamlMetadataAssertingPartyDetailsConverter.java
> +	public static final class AssertingPartyDetails extends RelyingPartyRegistration.AssertingPartyDetails {
I am wondering why you have decided to have an inner class instead `OpenSamlAssertingPartyDetails`?

2022-02-07 11:51 UTC, marcusdacoregio commented on saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/OpenSamlMetadataAssertingPartyDetailsConverter.java
> +		 * {@link org.springframework.security.saml2.provider.service.registration.OpenSamlAssertingPartyDetails.Builder}
```suggestion
		 * {@link org.springframework.security.saml2.provider.service.registration.OpenSamlMetadataAssertingPartyDetailsConverter.AssertingPartyDetails.Builder}
```

2022-02-07 11:51 UTC, marcusdacoregio commented on saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/OpenSamlMetadataAssertingPartyDetailsConverter.java
> +			 */
```suggestion
			/**
			 * Build an
			 * {@link org.springframework.security.saml2.provider.service.registration.OpenSamlMetadataAssertingPartyDetailsConverter.AssertingPartyDetails}
			 * @return the {@link org.springframework.security.saml2.provider.service.registration.OpenSamlMetadataAssertingPartyDetailsConverter.AssertingPartyDetails}
			 */
```

2022-02-07 11:51 UTC, marcusdacoregio commented on saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistration.java
> +	public static Builder withAssertingPartyDetails(AssertingPartyDetails assertingPartyDetails) {
Please update the copyright header of this class

2022-02-07 19:55 UTC, marcusdacoregio approved these changes

2022-02-07 21:42 UTC, merged