Allow custom relay state
spring-projects/spring-security pull request #11072
Opened 2022-04-07 09:09 UTC by exeba

This addresses issue #11065.

I've a couple of questions:

 - [OpenSamlAuthenticationRequestResolver.java](https://github.com/spring-projects/spring-security/compare/main...exeba:custom-relay-state?expand=1#diff-156c59b85e9f8743eb095ea6dc8b4603a9ad1999c0f7f4c9f75359aec2af9805) used to have all final fields. Is it ok to add a non-final field?
 - I tried to add a test case but it seems that ./gradelw test just compiles without executing the tests, am I missing something?

2022-04-07 09:09 UTC, pivotal-cla commented
@exeba Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=11072)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=11072) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2022-04-07 09:10 UTC, pivotal-cla commented
@exeba Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=11072)!

2022-04-07 15:21 UTC, jzheaux requested changes
Thanks, @exeba, for the quick turnaround!

For tests, please try running `./gradlew format check` and let me know if the tests run at that point.

2022-04-07 15:21 UTC, jzheaux commented on saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/OpenSamlAuthenticationRequestResolver.java
> +	private Converter<HttpServletRequest, String> relayStateResolver = (request) -> UUID.randomUUID().toString();
It's fine that this is non-final since it has a default configuration value.

2022-04-07 15:21 UTC, jzheaux commented on saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/OpenSamlAuthenticationRequestResolver.java
> +		String relayState = relayStateResolver.convert(request);
Please change to `this.relayStateResolver...` to fit with Spring Security's coding conventions.

2022-04-07 15:21 UTC, jzheaux commented on saml2/saml2-service-provider/src/opensaml4Main/java/org/springframework/security/saml2/provider/service/web/authentication/OpenSaml4AuthenticationRequestResolver.java
> +	 */
Please add `@since 5.7`

2022-04-07 15:21 UTC, jzheaux commented on saml2/saml2-service-provider/src/opensaml4Main/java/org/springframework/security/saml2/provider/service/web/authentication/OpenSaml4AuthenticationRequestResolver.java
> +		this.authnRequestResolver.setRelayStateResolver(relayStateResolver);
While unlikely, please check for `null` here by doing:

```java
Assert.notNull(relayStateResolver, "relayStateResolver cannot be null");
```

2022-04-07 16:06 UTC, exeba commented
@jzheaux I tried runnig `./gradlew format check`.
It seems that the majority of tests are run, but not the ones under `saml2/saml2-service-provider/src/test/`
The only way I can get a failure is with a syntax error. Maybe it is a problem with my environment

2022-05-05 23:44 UTC, jzheaux commented
Thanks, @exeba. Sorry for the delay, this is now merged in 4dfc349914cf7df9c4405d7f34b9f3a570b77cc1 and will go into the 5.8 release.

2022-05-05 23:44 UTC, closed without merging