gh-11039 Security Context Dsl
spring-projects/spring-security pull request #11111
Opened 2022-04-16 06:57 UTC by nor-ek

Add Security Context Dsl
- tests based on `SecurityContextConfigurerTests`
- security config dsl 

Closes gh-11039

2022-04-21 16:05 UTC, eleftherias requested changes
Thanks for the PR @nor-ek! I've left a few comments inline.

2022-04-21 16:05 UTC, eleftherias commented on config/src/main/kotlin/org/springframework/security/config/web/servlet/HttpSecurityDsl.kt
> + *          securityContext {
We shouldn't include setting the `securityContext` in this example, because it is meant to be a very basic example.

2022-04-21 16:05 UTC, eleftherias commented on config/src/main/kotlin/org/springframework/security/config/web/servlet/SecurityContextDsl.kt
> +    var securityContextRepository: SecurityContextRepository? = null
The `SecurityContextConfigurer` also allows users to set `requireExplicitSave`. We should allow the same functionality in the Kotlin DSL.

2022-04-22 10:27 UTC, nor-ek commented
@eleftherias I've fixed what you have mentioned.

2022-04-26 08:21 UTC, eleftherias commented on config/src/test/kotlin/org/springframework/security/config/web/servlet/SecurityContextDslTests.kt
> +    fun requireExplicitSave() {
This test name doesn't follow the expected format. The test name should describe the configuration and the expected result. The other tests in this file are named correctly.

2022-04-26 08:21 UTC, eleftherias commented
Thanks for the updates @nor-ek!
I've left one more comment above.

2022-04-26 13:20 UTC, nor-ek commented
Hey @eleftherias check if it's fine. I've also noticed that `SecurityContextPersistenceFilter` and more deprecated classes are used in `SecurityContextConfigurer`. Are you planning to replace it?

2022-04-26 15:34 UTC, eleftherias commented
Thanks @nor-ek! 
I will go ahead and merge the changes.

As for the `SecurityContextPersistenceFilter`, we have added an alternative `SecurityContextHolderFilter`. For now, we are keeping both classes.

2022-04-26 15:34 UTC, merged