Add workflow for scheduling releases on maintenance branches
spring-projects/spring-security pull request #11183
Opened 2022-05-04 19:09 UTC by sjohnr

Closes gh-11180

2022-05-06 20:36 UTC, rwinch requested changes
I've provided some feedback inline

2022-05-06 20:36 UTC, rwinch commented on .github/workflows/release-next-version.yml
>  name: Release Next Version
We should consider renaming release-next-version to something like update-scheduled-release-version

2022-05-06 20:36 UTC, rwinch commented on buildSrc/src/main/java/org/springframework/gradle/github/release/TriggerReleaseTask.java
> +public class TriggerReleaseTask extends DefaultTask {
I wonder if it might be GitHubDispatchWorkflowTask along with the ability to specify the workflow id to invoke.

2022-05-10 20:27 UTC, sjohnr commented
@rwinch I've updated the PR with some renaming and made the gradle task reusable.

2022-06-02 14:58 UTC, rwinch approved these changes

2022-06-03 15:19 UTC, merged