Change phoneNumberVerified with type Boolean
spring-projects/spring-security pull request #11317
Opened 2022-06-01 16:12 UTC by ziponia

Closes: gh-11315

2022-06-01 16:12 UTC, pivotal-cla commented
@ziponia Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=11317)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=11317) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2022-06-01 16:16 UTC, pivotal-cla commented
@ziponia Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=11317)!

2022-06-01 16:42 UTC, sjohnr requested changes
Thanks @ziponia! Please update the copyright year in the header to 2022 (see [contributing.adoc](https://github.com/spring-projects/spring-security/blob/main/CONTRIBUTING.adoc#update-apache-license-header-to-modified-files-as-necessary)). I have provided some additional feedback inline.

2022-06-02 19:49 UTC, sjohnr approved these changes

2022-06-02 19:52 UTC, sjohnr commented
Thanks for the updates @ziponia! I have approved this. However, did you see my request to update the copyright year in the header to 2022? If you aren't able to just let me know and I can take care of it.

2022-06-02 23:40 UTC, ziponia commented
sorry @sjohnr! I didn't see the request.
Just updated.

2022-06-03 14:46 UTC, merged