Change default authority for oauth2Login()
spring-projects/spring-security pull request #11887
Opened 2022-09-21 15:37 UTC by sjohnr

Previously, the default authority was `ROLE_USER` when using `oauth2Login()` for both OAuth2 and OIDC providers.

* Default authority for `OAuth2UserAuthority` is now `OAUTH2_USER`
* Default authority for `OidcUserAuthority` is now `OIDC_USER`

Documentation has been updated to include this implementation detail.

Closes gh-7856

2022-09-23 15:54 UTC, jgrandja requested changes
Thanks for the PR @sjohnr.

There are 2 minor updates needed and then please go ahead and merge.

Thanks!

2022-09-23 15:54 UTC, jgrandja commented on oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/oidc/user/OidcUserAuthority.java
>  	 */
Javadoc needs updating from ROLE_USER to OIDC_USER

2022-09-23 15:54 UTC, jgrandja commented on oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/user/OAuth2UserAuthority.java
>  	 * @param attributes the attributes about the user
Javadoc needs updating from ROLE_USER to OAUTH2_USER

2022-09-26 15:09 UTC, sjohnr commented
Merged via 181ee7410b2f4503d1d8513be68df510775fa958.

2022-09-26 15:09 UTC, closed without merging