Polish Span and Meter Names
spring-projects/spring-security pull request #12225
Opened 2022-11-16 21:25 UTC by jzheaux

2022-11-16 21:26 UTC, jzheaux commented
cc @jonatan-ivanov

2022-11-16 23:36 UTC, jonatan-ivanov requested changes

2022-11-16 23:36 UTC, jonatan-ivanov commented on web/src/main/java/org/springframework/security/web/ObservationFilterChainDecorator.java
> +			setContextualName("security filterchains " + filterSection);
Shouldn't this be singular (`security filterchain before/after`)?

2022-11-17 21:45 UTC, jonatan-ivanov approved these changes

2022-11-17 22:09 UTC, merged