Allow authorization request resolver to be changed for the OAuth2 client configuration
spring-projects/spring-security pull request #12438
Opened 2022-12-19 16:46 UTC by spoptchev

Fixes gh-12430. 

See issue for details.

2022-12-19 16:46 UTC, pivotal-cla commented
@spoptchev Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=12438)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=12438) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2022-12-19 16:49 UTC, pivotal-cla commented
@spoptchev Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=12438)!

2022-12-20 17:19 UTC, jgrandja requested changes
Thanks for the PR @spoptchev !

Can you also please add a test similar to `OAuth2LoginTests.oauth2LoginWhenCustomObjectsThenUsed()`. We should test if a custom `authorizationRequestResolver` is set then it is used. I think all you need to modify is `OAuth2ClientSpecTests.oauth2ClientWhenCustomObjectsThenUsed()`.

2022-12-20 17:19 UTC, jgrandja commented on config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java
> +		 */
Add `@since 6.1`

2022-12-21 07:56 UTC, spoptchev commented on config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java
> +		 */
Done 👍

2022-12-21 07:57 UTC, spoptchev commented
@jgrandja I added the test. Let me know if something is missing.

2022-12-22 16:29 UTC, jgrandja commented
Thanks for the updates @spoptchev. This is now merged.

FYI, I added a polish commit with some minor updates in order to get this merged as I am off until the new year.

Enjoy the holidays!

2022-12-22 16:29 UTC, closed without merging

2022-12-22 16:57 UTC, spoptchev commented
@jgrandja thank you for the integration.

Happy holidays 🎄