fixed Custom RelayState with OpenSamlLogoutRequestResolver
spring-projects/spring-security pull request #12565
Opened 2023-01-19 11:21 UTC by ghaege

2023-01-19 11:21 UTC, pivotal-cla commented
@ghaege Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=12565)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=12565) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-01-19 11:24 UTC, pivotal-cla commented
@ghaege Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=12565)!

2023-01-24 16:01 UTC, jzheaux requested changes
Thanks, @ghaege! New features need to go into the latest minor release, so will you please rebase on `main` so that this goes out in 6.1?

Also, will you please update your commit messages in the following two ways:
- The title should be in the present tense and should probably say "Add" instead of "Fix" (since this is new behavior)
- The commit message should have "Closes gh-12538" at the bottom, like this:

```
Add RelayState Customizer to SAML Logout

Closes gh-12538
```

2023-01-25 08:29 UTC, ghaege commented
replaced by https://github.com/spring-projects/spring-security/pull/12582

2023-01-25 08:29 UTC, closed without merging