Revisit Session Management docs
spring-projects/spring-security pull request #12601
Opened 2023-01-30 16:31 UTC by marcusdacoregio

Closes gh-12519

2023-02-06 21:18 UTC, jzheaux requested changes
Nice, @marcusdacoregio! I've left my feedback inline.

2023-02-13 13:50 UTC, marcusdacoregio commented on docs/modules/ROOT/pages/servlet/authentication/session-management.adoc
> +=== Configuring persistence for Stateless Authentication
I think I'll remove the `RequestCache` section and a ticket can be created to add some information about that.

2023-02-15 12:11 UTC, marcusdacoregio commented
Thanks, @jzheaux, I've addressed your suggestions and updated the PR. I also reverted [this commit](https://github.com/spring-projects/spring-security/pull/12601/commits/19ccbbaec598c9d857440b7b4e54c84eab6eb673) based on @rwinch feedback.

2023-02-15 21:55 UTC, jzheaux approved these changes
Such a huge improvement, @marcusdacoregio. Thanks for your efforts.

2023-02-16 13:40 UTC, merged