Add getters to `OAuth2AuthorizedClientId`
spring-projects/spring-security pull request #13648
Opened 2023-08-14 16:34 UTC by ch4mpy

The current implementation of `OAuth2AuthorizedClientId` is enough to compare IDs, but I have a use case where I retrieve some if this IDs and need to access the registration ID, which is not possible right now.

2023-09-23 09:43 UTC, willns1 approved these changes

2023-12-20 01:14 UTC, jzheaux requested changes
Thanks, @ch4mpy. WIll you do me a couple of favors here, please?

1. Update the copyright year
2. Add JavaDoc. I realize that getter JavaDoc is sometimes a little cookie cutter; in this case it at least gives a place for a `@since` attribute.

2024-02-27 13:54 UTC, ch4mpy commented
@jzheaux finally done

2024-04-18 21:55 UTC, sjohnr commented
Thanks @ch4mpy! This is now merged as b69939c1e55c9dd477e55e91f6d783ae720c18ec with polish commit 05d3beb6a845712a10a405655170007340ce2cc0.

2024-04-18 21:55 UTC, closed without merging