Add DelegatingAuthenticationConverter
spring-projects/spring-security pull request #14655
Opened 2024-02-27 08:04 UTC by franticticktick

Closes gh-14644

2024-03-03 21:52 UTC, CrazyParanoid commented
@jzheaux Can you review this please? I will be very grateful.

2024-03-06 22:55 UTC, jzheaux requested changes
Thanks, @CrazyParanoid! I've left my feedback inline.

2024-03-06 22:55 UTC, jzheaux commented on web/src/main/java/org/springframework/security/web/authentication/DelegatingAuthenticationConverter.java
> +public class DelegatingAuthenticationConverter implements AuthenticationConverter {
Please make the class `final`. This simplifies maintenance long-term and is something that we can change in the future.

2024-03-06 22:55 UTC, jzheaux commented on web/src/main/java/org/springframework/security/web/authentication/DelegatingAuthenticationConverter.java
> +		this.delegates = delegates;
Please make a copy so that the ability to modify the list doesn't leak outside of the instance.

2024-03-06 22:55 UTC, jzheaux commented on web/src/main/java/org/springframework/security/web/authentication/DelegatingAuthenticationConverter.java
> +		return this.delegates.stream()
Please avoid streams due to #7182

2024-03-07 09:25 UTC, CrazyParanoid commented
Thanks @jzheaux for feedback! All your comments have been resolved.

2024-03-13 20:28 UTC, jzheaux approved these changes

2024-03-13 20:33 UTC, merged