Improved error message for PasswordEncoder
spring-projects/spring-security pull request #14968
Opened 2024-04-26 13:14 UTC by bottlerocketjonny

I fear I might have been too slow to submit this! However, this closes gh-14880

Happy to make any changes.

2024-04-26 23:13 UTC, jzheaux commented
Hi, @bottlerocketjonny! Yes, we already received another PR for the same and I think it is a nice improvement. That said, if you'd like, please rebase once that is merged and push any other changes you'd like to see to this PR, and we can take a look together.

2024-04-27 07:09 UTC, bottlerocketjonny commented
> Hi, @bottlerocketjonny! Yes, we already received another PR for the same and I think it is a nice improvement. That said, if you'd like, please rebase once that is merged and push any other changes you'd like to see to this PR, and we can take a look together.

No worries! Yeah sure thing I shall do that 👍🏻

Just for future reference, if I wanted to work on an issue should I wait to be assigned or just go for it? I left a comment on this one but wasn't sure if that was the way to go. Cheers 😀

2024-05-21 22:33 UTC, jzheaux commented
@bottlerocketjonny, it's certainly better when I'm on top of folks' comments in tickets so that there isn't confusion. :) Sorry that you and the other contributor ended up working on the same feature.

It's rare for two people to contribute near the same time, so we don't have a stated policy. Mostly, it's a best effort on my part to notice the comment, assign the issue to that person, and in the absence of that, attend to the first submitted PR.

In your case, I'm happy that there were good ideas in both PRs, so I'd still encourage you to rebase.

2024-05-31 18:29 UTC, jzheaux requested changes
Thanks for the updates, @bottlerocketjonny! I've left some feedback inline.

Also, will you please update your commit message to include the ticket https://github.com/spring-projects/spring-security/issues/14880 like so:

```
Your Title

Issue gh-14880
```

That will link this work to that ticket in GitHub, making it easier to track in the future.

2024-05-31 18:29 UTC, jzheaux commented on crypto/src/main/java/org/springframework/security/crypto/password/DelegatingPasswordEncoder.java
> +		if (start == -1 && !prefixEncodedPassword.contains(this.idSuffix)) {
I'd like to be a bit more conservative with changing this behavior, given that it is called by more than one flow in this class. What if the `matches` implementation itself did the needed checking? Something like this:

```java
String id = extractId(prefixEncodedPassword);
if (has a value) {
    throw no mapping exception
}
start = indexof idPrefix
end = indexof idSuffix, start
if (start < 0 && end < 0) {
    throw no encoder prefix 
}
throw malformed encoder prefix
```

In exchange for a small amount of duplication, we don't change the expectations of other flows calling `extractId`.

2024-05-31 18:29 UTC, jzheaux commented on crypto/src/main/java/org/springframework/security/crypto/password/DelegatingPasswordEncoder.java
> +				throw new IllegalArgumentException("Password encoding information cannot be null. " +
I think another bit of advice is needed here. Something like:

```
Given that there is no default password encoder configured, each password must have a password encoding prefix. Please either prefix this password with '{noop}' or set a default password encoder in `DelegatingPasswordEncoder`.
```

2024-05-31 18:29 UTC, jzheaux commented on core/src/test/java/org/springframework/security/provisioning/InMemoryUserDetailsManagerTests.java
> +import java.util.stream.Stream;
Please update the copyright here to `2002-2024`

2024-05-31 18:29 UTC, jzheaux commented on crypto/src/main/java/org/springframework/security/crypto/password/DelegatingPasswordEncoder.java
> -		if (start != 0) {
Please update the copyright here to `2002-2024`

2024-05-31 18:29 UTC, jzheaux commented on crypto/src/test/java/org/springframework/security/crypto/password/DelegatingPasswordEncoderTests.java
> -			.withMessage("There is no PasswordEncoder mapped for the id \"unmapped\"");
Please update the copyright here to `2002-2024`

2024-08-19 16:18 UTC, bottlerocketjonny commented
@jzheaux Oh gosh, so sorry I completely missed that you'd replied here. I'll get this sorted ASAP so we can close this issue.

2024-09-07 15:59 UTC, bottlerocketjonny commented
@jzheaux I've just pushed some new commits that I think are an improvement - let me know if anything else needs changing and apologies again for my tardiness! :)

2024-09-17 21:15 UTC, jzheaux approved these changes

2024-09-17 21:16 UTC, merged

2024-09-17 21:16 UTC, jzheaux commented
Thanks, @bottlerocketjonny! This is now merged into `main`.

2024-09-18 04:56 UTC, bottlerocketjonny commented
> Thanks, @bottlerocketjonny! This is now merged into `main`.

Excellent! Thanks for your patience.