Improving Code Readability and Efficiency: Refactoring Redundant Conditionals
spring-projects/spring-security pull request #14977
Opened 2024-04-27 16:48 UTC by dukbong

### Original Code:
The given code snippets retrieve authorized clients from a WebSession and return a map of OAuth2 authorized clients. Both snippets handle null values to prevent errors, but the second snippet achieves the same functionality in a more concise and readable way.

### Refactoring Suggestion:

- Replace the first code snippet with the second, which simplifies the conditional check for null and reduces redundant code.
- Use the ternary operator to assign a default empty HashMap if the session attribute or the session itself is null. This reduces code complexity while maintaining clarity.

2024-05-02 23:35 UTC, dukbong commented
> Hi @dukbong, thanks for the PR!
> 
> 
> 
> Just a heads up, I closed the original issue with [this explanation](https://github.com/spring-projects/spring-security/issues/14975#issuecomment-2090702647). I appreciate what you're doing in this change by asserting the session cannot be null. I'm wondering though if this change is absolutely necessary?
> 
> 
> 
> > This code does not explicitly assert that WebSession cannot be null, potentially leading to silent failures or unexpected behavior.
> 
> 
> 
> Can you explain the situation in which this would occur (other than the invalid configuration referred to in the original issue)?


Hi @sjohnr 

Initially, I planned to submit a pull request to address the issue, but as I reviewed the code, I found the structure to be questionable, prompting a change in direction.

The `getAuthorizedClient` function is written with the assumption that the session might be null. However, if the session is null, this leads to an exception in the `saveAuthorizedClient` function. To prevent this, I believe it's better to ensure the session isn't null either in the `getAuthorizedClient` function or in the `doOnSuccess` block.

Based on these observations, I created a pull request to address the issue.

- Your feedback is invaluable for my growth and learning.

2024-05-03 14:55 UTC, sjohnr requested changes
Thanks for the PR @dukbong. In addition to the feedback inline below, can you please add a test that asserts an `IllegalArgumentException` is thrown when `WebSession` is null?

2024-05-03 14:55 UTC, sjohnr commented on oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/server/WebSessionServerOAuth2AuthorizedClientRepository.java
> +
Please remove this extra newline.

2024-05-03 14:55 UTC, sjohnr commented on oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/server/WebSessionServerOAuth2AuthorizedClientRepository.java
Please update the copyright year in the header as per [contributing guidelines](https://github.com/spring-projects/spring-security/blob/main/CONTRIBUTING.adoc#submit-a-pull-request).

2024-05-03 14:55 UTC, sjohnr commented on oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/server/WebSessionServerOAuth2AuthorizedClientRepository.java
> +	    return authorizedClients != null ? authorizedClients : new HashMap<>();
You can add parentheses around the ternary condition to satisfy checkstyle and allow the build to pass.

2024-05-03 14:55 UTC, sjohnr commented on oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/server/WebSessionServerOAuth2AuthorizedClientRepository.java
> +		Assert.notNull(session, "WebSession cannot be null. Ensure the session is properly initialized before accessing authorized clients.");
I think the message can simply be `session cannot be null`.

2024-05-03 15:35 UTC, dukbong commented
> Thanks for the PR @dukbong. In addition to the feedback inline below, can you please add a test that asserts an `IllegalArgumentException` is thrown when `WebSession` is null?

Thanks @sjohnr  for agreeing with my feedback.
I will make the changes and additions as per the comments below!

2024-05-06 17:31 UTC, sjohnr reviewed
Thanks @dukbong. I added one minor comment below. Can you also please rebase your changes on main and squash commits? I will schedule this to be merged in the next minor so you won't see it merged for a few weeks.

2024-05-06 17:31 UTC, sjohnr commented on oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/server/WebSessionServerOAuth2AuthorizedClientRepository.java
> -	@SuppressWarnings("unchecked")
I don't think this should be removed. Can you restore this line?

2024-05-07 00:43 UTC, dukbong commented
> Thanks @dukbong. I added one minor comment below. Can you also please rebase your changes on main and squash commits? I will schedule this to be merged in the next minor so you won't see it merged for a few weeks.


Hello. @sjohnr 

As you suggested, I rebased onto the main branch and squashed the commits into one.

If there's anything I did wrong or need to correct, please let me know!
I'll fix it right away!!

2024-05-29 19:16 UTC, sjohnr commented on oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/server/WebSessionServerOAuth2AuthorizedClientRepository.java
> -	@SuppressWarnings("unchecked")
Apologies as you were correct to remove this. I'll re-remove it in a polish commit.

2024-05-29 21:27 UTC, sjohnr commented
Thanks @dukbong, this is now merged into `5.8.x` as 1695d03b72d9d48f24abd8381f5f120b99a7f7a1. I did apply a polish commit with some adjustments because I didn't run the build to see checkstyle and other build output, so check out 
e34621ec2ced820accc121b053752387d053d9a5 and let me know if you have questions.

2024-05-29 21:27 UTC, closed without merging