instanceof changed to recent syntax
spring-projects/spring-security pull request #15033
Opened 2024-05-09 08:29 UTC by dukbong

instanceof changed to recent syntax

2024-05-13 12:19 UTC, marcusdacoregio requested changes
Thanks @dukbong, I've left a feedback inline.

2024-05-13 12:19 UTC, marcusdacoregio commented on core/src/main/java/org/springframework/security/authentication/AbstractAuthenticationToken.java
> +		if (secret instanceof CredentialsContainer secret) {
The variable name `secret` is already defined in the scope, can you please rename it to maybe `container`?

2024-05-14 14:08 UTC, marcusdacoregio commented
In preparation to merge, can you please squash your commits?

The single commit message could be: `Use instanceof Pattern Matching `

2024-05-14 17:00 UTC, closed without merging

2024-05-14 17:13 UTC, dukbong commented
> In preparation to merge, can you please squash your commits?
> 
> The single commit message could be: `Use instanceof Pattern Matching `

I'm sorry. @marcusdacoregio 

My mistake caused the PR to be removed.

I will submit a new PR.