Add setter method for userDetailsChecker in CasAuthenticationProvider(#10277)
spring-projects/spring-security pull request #15047
Opened 2024-05-12 11:50 UTC by Kyoungwoong

This commit introduces a setter method for the userDetailsChecker property in the CasAuthenticationProvider class. Previously, the userDetailsChecker was initialized with a default AccountStatusUserDetailsChecker instance, limiting customization options. Now, users can inject their own UserDetailsChecker implementation through the setter method, providing greater flexibility in handling user details validation.

fixes: #10277

2024-05-12 11:50 UTC, pivotal-cla commented
@Kyoungwoong Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=15047)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=15047) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2024-05-12 11:54 UTC, pivotal-cla commented
@Kyoungwoong Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=15047)!

2024-05-12 12:05 UTC, injae-kim commented on cas/src/main/java/org/springframework/security/cas/authentication/CasAuthenticationProvider.java
> +	public void setUserDetailsChecker(UserDetailsChecker userDetailsChecker) {
```suggestion
	public void setUserDetailsChecker(final UserDetailsChecker userDetailsChecker) {
```

2024-05-13 12:26 UTC, marcusdacoregio requested changes
Thanks for the PR @Kyoungwoong, I've left some feedback inline.

Can you please add a test that makes sure that when setting the `UserDetailsChecker` it is used where needed?

2024-05-13 12:26 UTC, marcusdacoregio commented on cas/src/main/java/org/springframework/security/cas/authentication/CasAuthenticationProvider.java
> + * Copyright 2004, 2005, 2006, 2024 Acegi Technology Pty Limited
We don't typically change copyright notices from Acegi, you can leave it as it was.

```suggestion
 * Copyright 2004, 2005, 2006 Acegi Technology Pty Limited
```

2024-05-13 12:26 UTC, marcusdacoregio commented on cas/src/main/java/org/springframework/security/cas/authentication/CasAuthenticationProvider.java
> +		this.userDetailsChecker = userDetailsChecker;
Can you please verify that the `userDetailsChecker` is not null?

```suggestion
        Assert.notNull(userDetailsChecker, "userDetailsChecker cannot be null");
		this.userDetailsChecker = userDetailsChecker;
```

2024-05-13 12:26 UTC, marcusdacoregio commented on cas/src/main/java/org/springframework/security/cas/authentication/CasAuthenticationProvider.java
> +	 * @param userDetailsChecker the UserDetailsChecker to be set
Please add `@since 6.4`

2024-05-20 08:38 UTC, Kyoungwoong commented
All review has been resolved.

2024-05-24 17:00 UTC, merged

2024-05-24 17:01 UTC, marcusdacoregio commented
Thanks @Kyoungwoong. This is now merged into `main`.