Refactoring Test Code to Reduce Duplication of Mock Object Creation for Issue#14768
spring-projects/spring-security pull request #15396
Opened 2024-07-11 05:45 UTC by gzhao9

Hi there,

This PR is to address [issue #14768](https://github.com/spring-projects/spring-security/issues/14768), which involves reducing repeated mock object creation in tests. 

I mistakenly closed PR #15256 and then discovered that I do not have permission to reopen it, receiving the message `this branch was force pushed or recreated.`  I'm not sure if I should reopen the original or create this new PR 

Although my issue submission mentioned 4 separate draft PRs, I combined them into this PR, since they all address the same problem.

2024-07-11 05:48 UTC, gzhao9 commented
@jesperronn Please feel free to let me know if there is anything I need to change. I look forward to your suggestions.

2024-07-18 22:44 UTC, jzheaux requested changes
Thanks for the idea, @gzhao9. I think there is already a `MockSecurityContextHolderStrategy` available in `spring-security-core`. Can you please enhance that instead?

I think it would be reasonable to add the default constructor and one that takes a `SecurityContext` to that class.

Please also run `./gradlew format && ./gradlew check` before committing next. It appears there are some formatting issues that those two tasks will help you work through.

When you are done, will you please change your commits to be more descriptive in the following way. For each commit, describe what you've done and include the issue number like so:

```
Use MockSecurityContextHolderStrategy

Issue gh-14768
```

For the final commit, please use `Closes gh-14768` instead as this integrates with our build system to close the issue automatically.

2024-09-17 21:12 UTC, jzheaux requested changes
Thank you for the PR, @gzhao9. I've left feedback inline.

Additionally, will you please consider whether you can follow the same strategy for all four files when it comes to setting up mocks? It seems that in one you have a separate class, in another you have a field and a `setup` method, and in others you use a local method. It would be nice if the code can be more consistent.

Finally, will you please ensure that your commits are in the following format:

```
Factor out common SecurityContextHolderStrategy mocking
```

or similar, depending on the work done for each file.
```

2024-09-17 21:12 UTC, jzheaux commented on ldap/src/test/java/org/springframework/security/ldap/authentication/ad/ActiveDirectoryLdapAuthenticationProviderTests.java
> -		given(ctx.getNameInNamespace()).willReturn("");
I'd like the tests to remain as similar as possible behaviorally. Will you then please add this to the setup method:

```java
given(ctx.getNameInNamespace()).willReturn("");
```

2024-09-17 21:12 UTC, jzheaux commented on web/src/test/java/org/springframework/security/web/access/ExceptionTranslationFilterTests.java
> +	private FilterChain mockFilterChainWiehException(Object exception) throws ServletException, IOException {
I believe there is a typo here and the method should be called `mockFilterChainWithException`.

2024-09-17 21:12 UTC, jzheaux commented on web/src/test/java/org/springframework/security/web/access/ExceptionTranslationFilterTests.java
> +	private FilterChain mockFilterChainWiehException(Object exception) throws ServletException, IOException {
I think this method can take `Exception` for the parameter type. Is there a reason it needs to be `Object`?

2024-09-17 21:12 UTC, jzheaux commented on web/src/test/java/org/springframework/security/web/access/ExceptionTranslationFilterTests.java
> +		willThrow((Throwable) exception).given(fc).doFilter(any(HttpServletRequest.class), any(HttpServletResponse.class));
If you can change the parameter type, this cast should be removed.

2024-09-23 20:47 UTC, gzhao9 commented
> Thanks for the cleanup, @gzhao9. I think there is already a `MockSecurityContextHolderStrategy` available in `spring-security-core`. Can you please enhance that instead?
> 
> I think it would be reasonable to add the default constructor and one that takes a `SecurityContext` to that class.
> 
> Please also run `./gradlew format && ./gradlew check` before committing next. It appears there are some formatting issues that those two tasks will help you work through.
> 
> When you are done, will you please change your commits to be more descriptive in the following way. For each commit, describe what you've done and include the issue number like so:
> 
> ```
> Use MockSecurityContextHolderStrategy
> 
> Issue gh-14768
> ```
> 
> For the final commit, please use `Closes gh-14768` instead as this integrates with our build system to close the issue automatically.

I found `MockSecurityContextHolderStrategy` in `spring-security-core`. However, since they are not in the same package, I would need to change the dependency if I want to reference `MockSecurityContextHolderStrategy` in `org.springframework.security.authorization.method`. I believe adding new dependencies should be considered carefully. Therefore, I only added a private method in each test class.

2024-09-24 14:43 UTC, gzhao9 commented
I first focus on each file code modification. I will rebase commits when there is no need to modify the code or format.

2024-09-26 18:52 UTC, jzheaux commented
Thanks for the updates, @gzhao9! I think there are two other items from the review that haven't been addressed yet. Are you able to do those as well?

2024-09-28 12:05 UTC, gzhao9 commented
> Thanks for the updates, @gzhao9! I think there are two other items from the review that haven't been addressed yet. Are you able to do those as well?

I have modified the code as required.

2024-10-23 22:35 UTC, jzheaux approved these changes

2024-10-25 03:51 UTC, merged

2024-10-25 03:51 UTC, jzheaux commented
Thanks, @gzhao9! This is now merged into `main`.