Fix explanation for HttpSessionCsrfTokenRepository
spring-projects/spring-security pull request #15392
Opened 2024-07-10 12:45 UTC by Junhyunny

I fixed the explanation about HttpSessionCsrfTokenRepository class. This class loads CRSF token from and save into a session.

2024-07-22 22:15 UTC, jzheaux requested changes
Thanks, @Junhyunny! Please see my inline feedback.

Also, are you able to rebase the PR on `5.8.x` so all the documentation gets this correction? If not, that's a step I can do for you.

2024-07-22 22:15 UTC, jzheaux commented on docs/modules/ROOT/pages/servlet/exploits/csrf.adoc
> +The `HttpSessionCsrfTokenRepository` reads the token from a session(e.g. in-memory, cache or database). Default session attribute name is `HttpSessionCsrfTokenRepository.class.getName().concat(".CSRF
For clarity, please change the wording to:

> a session (whether in-memory, cache, or database). If you need to access the session attribute directly, please first configure the session attribute name using `HttpSessionCsrfTokenRepository#setSessionAttributeName`.

The main change here is to leave out the default. Since the attribute name is private, I'd prefer not to imply that it is part of the public API by documenting it. I've also made some grammatical polishes.

2024-07-25 14:18 UTC, Junhyunny commented
> Thanks, @Junhyunny! Please see my inline feedback.
> 
> Also, are you able to rebase the PR on `5.8.x` so all the documentation gets this correction? If not, that's a step I can do for you.

I tried to rebase this branch on 5.8.x. There are some conflicts so this seems quite tough. Could you help me?

2024-07-25 14:42 UTC, Junhyunny commented
> Thanks, @Junhyunny! Please see my inline feedback.
> 
> Also, are you able to rebase the PR on `5.8.x` so all the documentation gets this correction? If not, that's a step I can do for you.

Do you mean make a new PR from 5.8.x. So you can easily merge into 6.2.x, 6.3.x and main finally.

2024-07-29 20:02 UTC, jzheaux commented
No problem, @Junhyunny, I'll take care of it!

It appears that the first instance of this bug is on `6.2.x`, so I've rebased to that instead.

2024-07-29 21:07 UTC, jzheaux approved these changes

2024-07-29 21:08 UTC, merged