Fix NPE when nameAttributeValue is null (#15338)
spring-projects/spring-security pull request #15407
Opened 2024-07-12 12:53 UTC by HyoJongPark

This commit resolves NPEs that occur in DefaultOuth2User#getName.
If the attributes have a key, but the value comes in null, the NPE occurs, and we modified the case and added a related test case.

fixes: #15338

2024-07-12 12:53 UTC, pivotal-cla commented
@HyoJongPark Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=15407)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=15407) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2024-07-12 17:03 UTC, jzheaux requested changes
Thanks! I've left some feedback inline.

Also, when you are ready, will you please squash your commits so that there is only one? Please format that final commit like so:

```
Check for null Name Attribute Value

Closes gh-15338
```

2024-07-12 17:03 UTC, jzheaux commented on oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/user/DefaultOAuth2User.java
> +		Assert.notNull(attributes.get(nameAttributeKey), "Name attribute '" + nameAttributeKey + "' cannot be null");
I think `Map#get` returing `null` implies that `Map#containsKey` returns `false`.

Would you please then simply replace the `containsKey` check with the `nonNull` check?

Please change the message also to:

```
Assert.notNull(attributes.get(nameAttributeKey), "Attribute value for '" + nameAttributeKey + "' cannot be null");
```

2024-07-12 23:02 UTC, HyoJongPark commented
All review has been resolved and reformat commit.!

2024-07-18 23:39 UTC, merged

2024-07-18 23:39 UTC, jzheaux commented
Thanks, @HyoJongPark! This is now merged into `main`.