Add cookie customizer to CookieRequestCache
spring-projects/spring-security pull request #15685
Opened 2024-08-23 16:57 UTC by fb64

Issue gh-15286

2024-08-29 14:04 UTC, marcusdacoregio requested changes
Thanks for the PR @fb64. I've left a single feedback inline.

Would you please add the same support in `CookieServerRequestCache`? I believe that the only difference is that the `cookieCustomizer` would be a `Consumer<ResponseCookie.Builder>`

2024-08-29 14:04 UTC, marcusdacoregio commented on web/src/main/java/org/springframework/security/web/savedrequest/CookieRequestCache.java
> +	 * @param cookieCustomizer customize for cookie
Can you please add `@since 6.4`?

2024-08-29 19:24 UTC, fb64 commented
> Thanks for the PR @fb64. I've left a single feedback inline.
> 
> Would you please add the same support in `CookieServerRequestCache`? I believe that the only difference is that the `cookieCustomizer` would be a `Consumer<ResponseCookie.Builder>`

As far as I know `ResponseCookie` is used by reactive stack and cannot directly used in a standard `HttpServletResponse` unless refactoring the class, that's why I used a consumer of the same `Cookie` object already used. 
It's very similar to https://github.com/spring-projects/spring-security/pull/15203

2024-08-30 17:08 UTC, marcusdacoregio commented
Hi @fb64, I'm sorry if what I said was confusing. But I mean that the reactive implementation should be a `Consumer<ResponseCookie.Builder>`. Does that make sense?

2024-08-31 12:43 UTC, fb64 commented
> Hi @fb64, I'm sorry if what I said was confusing. But I mean that the reactive implementation should use a `Consumer<ResponseCookie.Builder>`. Does that make sense?

Got it, I added it to `CookieServerRequestCache`  sorry for the misunderstanding 😅

2024-09-03 12:41 UTC, merged

2024-09-03 12:41 UTC, marcusdacoregio commented
Thanks @fb64, this is now merged into `main`.