Improve Cglib Object serialize
spring-projects/spring-security pull request #15687
Opened 2024-08-25 01:45 UTC by kse-music

Closes gh-15661

2024-08-26 04:56 UTC, kse-music commented
@jzheaux I wonder why the spring-security-saml2-service-provider:opensaml4Test task  execution failed , and I didn’t make any changes.

2024-08-26 22:01 UTC, jzheaux requested changes
Thanks for the PR, @kse-music! Please see my inline feedback.

2024-08-26 22:29 UTC, jzheaux commented
@kse-music there is a flaky test in that module. It has been disabled for now. Please try rebasing an push to your branch again.

2024-08-27 06:57 UTC, kse-music commented on core/src/main/java/org/springframework/security/authorization/method/AuthorizationAdvisorProxyFactory.java
> +	public interface AuthorizeReturnObject {
Done

2024-08-27 06:58 UTC, kse-music commented on docs/modules/ROOT/pages/servlet/authorization/method-security.adoc
> +Or register `AuthorizeReturnObjectJackson2Module` to `ObjectMapper`:
Done

2024-08-27 06:58 UTC, kse-music commented on core/src/test/java/org/springframework/security/authorization/AuthorizationAdvisorProxyFactoryTests.java
> +	@Test
Done

2024-08-27 07:37 UTC, kse-music commented
@jzheaux I have completed the feedback, please help review it. Thanks

2024-08-29 23:46 UTC, jzheaux commented
@kse-music, having researched this a bit further, I believe there is a more elegant way to achieve this and that is by configuring with `ProxyFactory#setOpaque(true)`. This will keep from exposing the advice methods on the CGLIB proxy altogether, preventing the cycle.

Would you be able to update this PR to set the `opaque` value to `true` for both `ProxyFactory` instances in `AuthorizationAdvisorProxyFactory`? Also, please add a test in `AuthorizationAdvisorProxyFactory` that confirms that JSON serialization works with a POJO and an out-of-the-box `ObjectMapper`.

Please also remove the entire `Working with Jackson` section as no Jackson configuration is necessary in this case.

2024-08-30 02:07 UTC, kse-music commented
@jzheaux PR has been updated

2024-08-30 17:40 UTC, jzheaux approved these changes

2024-08-30 17:40 UTC, merged

2024-08-30 18:29 UTC, jzheaux commented
Thanks, @kse-music! This is now merged into `main`