Use SessionAuthenticationStrategy for Remember-Me authentication
spring-projects/spring-security pull request #15748
Opened 2024-09-06 06:53 UTC by xhaggi

As described in gh-2253, the `RememberMeAuthenticationFilter` does not call the configured `SessionAuthenticationStrategy` if there is one, and therefore concurrent session control does not work properly.

This PR adapts the `RememberMeAuthenticationFilter` so that it calls the `SessionAuthenticationStrategy` on successful authentication as the `AbstractAuthenticationProcessingFilter` does. The shared `SessionAuthenticationStrategy` is then used in the `RememberMeConfigurer` to configure the filter.

Let me know if anything is missing!

2024-09-17 01:12 UTC, jzheaux requested changes
Thanks for the PR, @xhaggi! Could you add a unit test that confirms the desired behavior (concurrency control) works, for example when the DSL configures a max number of sessions and the remember me filter exceeds that?

2024-10-01 08:15 UTC, xhaggi commented
@jzheaux of course. I have added the unit test.

2024-10-14 18:47 UTC, jzheaux approved these changes

2024-10-15 09:15 UTC, xhaggi commented
@jzheaux the [build](https://github.com/spring-projects/spring-security/actions/runs/11121314806/job/31517224220) failed because formatting violations were found in the files I changed. I fixed it and force-pushed the changes.

2024-10-15 09:18 UTC, xhaggi commented
BTW is there any chance that this will be backported to earlier versions?

2024-10-15 17:51 UTC, jzheaux commented
Hi, @xhaggi, no, it's not likely, given that there is a behavioral change and a new public API. That said, what version were you hoping to backport it to and what is preventing you from upgrading?

2024-10-15 21:07 UTC, merged

2024-10-16 09:11 UTC, xhaggi commented
>what version were you hoping to backport

I was thinking of the last stable version 6.3.x.

>what is preventing you from upgrading

Nothing, but we have to wait for the next stable 😉