Avoid UriComponentsBuilder.fromUri
spring-projects/spring-security pull request #15853
Opened 2024-09-25 15:01 UTC by bodograumann

Closes #15852

By using `UriComponentsBuilder.fromUriString` we stay in a single semantic context and do not loose information.

2024-09-25 15:01 UTC, pivotal-cla commented
@bodograumann Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=15853)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=15853) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2024-09-25 15:03 UTC, pivotal-cla commented
@bodograumann Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=15853)!

2024-09-26 18:01 UTC, jzheaux requested changes
Thanks for the PR, @bodograumann! WIll you please also add a test for both servlet and reactive that show that this behavior is now repaired?

2024-09-26 18:11 UTC, jzheaux commented
Thinking about this more, while it may still be valuable for this PR to have these tests, it seems to me that @rstoyanchev [is open to](https://github.com/spring-projects/spring-framework/issues/27774#issuecomment-1004757583) updating `UriComponentsBuilder`. I think it would be better to focus on addressing the issue in Framework first. Have you already considered submitting a PR there?

2024-09-27 05:28 UTC, bodograumann commented
True, fixing the underlying issue in UriComponentsBuilder would be preferrable, but I focused on what I could get done in limited time.
I'll try to look into adding a test, which will require somehow mocking the RestTemplate and maybe I'll also find time to understand the difference between authority and host enough to propose a solution for UriComponentsBuilder.

2024-09-27 14:45 UTC, rstoyanchev commented
The challenge with re-parsing the authority is having to extract the parsing logic out of the whole algorithm. Couldn't you re-parse the full URI string in fallback mode? Something like:

```java
URI uri = URI.create(issuer);
if (uri.getHost() == null && getAuthority() != null) {
    uri = UriComponentsBuilder.fromUriString(issuer).build().toURI();
}
```

2024-09-30 11:46 UTC, bodograumann commented
That makes sense @rstoyanchev .
Also I couldn't find a way to mock the RestTemplate here, so I create a PR for the spring framework: https://github.com/spring-projects/spring-framework/pull/33614

2024-10-09 12:57 UTC, bodograumann commented
> The challenge with re-parsing the authority is having to extract the parsing logic out of the whole algorithm. Couldn't you re-parse the full URI string in fallback mode? Something like:
> 
> ```java
> URI uri = URI.create(issuer);
> if (uri.getHost() == null && getAuthority() != null) {
>     uri = UriComponentsBuilder.fromUriString(issuer).build().toURI();
> }
> ```
> 
> This would impact only such URI's, and minimize any potential disruption for all others.

Given that since https://github.com/spring-projects/spring-framework/commit/bbb53d03c4f9f65b8bfaca92fbd1e88aabf6e347 `UriComponentsBuilder` uses the RFC 3986 parser by default, we are here only switching from RFC 2396 to RFC 3986 URI parsing, not to WhatWG parsing anymore.
Do you still think the impact would be too great, @rstoyanchev ?

As for testing: Could I make the `oidc`, `oidcRfc8414` and `oauth` methods package protected and test them directly? Testing anything involving `getConfiguration` and the RestTemplate seems unfeasible to me, when we want to vary the hostname.

2025-02-20 23:54 UTC, merged

2025-02-20 23:56 UTC, jzheaux commented
Thanks for the PR, @bodograumann! And I'm sorry for the extended delay.

In my testing, I found another issue with using `URI` and so I've adjusted these classes and `ClientRegistrations` to not use it. You can see these efforts in 571135d2ab06b24d30c91249ca8c7d0b0285a346 and 49e5d3796e019d8ba03c68481e7c1a4327cad751