Catch base64 decode exception
spring-projects/spring-security pull request #15914
Opened 2024-10-14 08:22 UTC by kse-music

Closes gh-15905

2024-10-14 18:28 UTC, jzheaux requested changes
Thanks, @kse-music! I've left some feedback inline. Also, please update the copyright years to any non-Acegi copyright messages.

2024-10-14 18:28 UTC, jzheaux commented on web/src/main/java/org/springframework/security/web/savedrequest/CookieRequestCache.java
> +			return null;
Let's please at least log the exception so that it isn't lost. `DEBUG` should be suitable.

2024-10-23 22:31 UTC, jzheaux commented
Thanks for the updates, @kse-music! Can you please update the copyright for the test file as well?

2024-10-24 02:06 UTC, kse-music commented
@jzheaux I have been updated

2024-10-24 17:12 UTC, jzheaux approved these changes

2024-10-24 17:55 UTC, merged

2024-10-24 17:59 UTC, jzheaux commented
Thanks, @kse-music! This is now merged into `5.8.x` as well as the other branches.