Polish DelegatingAuthenticationConverter
spring-projects/spring-security pull request #15949
Opened 2024-10-18 05:19 UTC by kse-music

Use List.of instead of new ArrayList

2024-10-18 09:59 UTC, CrazyParanoid commented on web/src/main/java/org/springframework/security/web/authentication/DelegatingAuthenticationConverter.java
> +		this.delegates = delegates;
Hi @kse-music , delegates passed to the constructor must be wrapped in a new list, only then can we suggest that they not be changed from the outside. Your solution is not safe in this regard, so I suggest leaving it as it is.

2024-10-23 18:05 UTC, jzheaux requested changes
@kse-music, thanks for this improvement. Please see my inline feedback.

Also, since the constructors demonstrate different behavior, I think this is a bug and should be fixed in `6.3.x` as well. Are you able to rebase this change to `6.3.x` please?

2024-10-23 18:05 UTC, jzheaux commented on web/src/main/java/org/springframework/security/web/authentication/DelegatingAuthenticationConverter.java
> +		this(List.of(delegates));
I'm not a huge fan of recreating the list twice. Could we please leave this constructor as-is, even though that duplicates the null check?

2024-10-23 18:08 UTC, jzheaux commented
Also, @kse-music, I updated the PR title and description to reflect some of the API benefits to this change.

2024-10-24 02:16 UTC, kse-music commented
Thanks a lot, @jzheaux. Everything is done as you expected.

2024-10-25 03:44 UTC, jzheaux approved these changes

2024-10-25 03:47 UTC, merged

2024-10-25 03:48 UTC, jzheaux commented
Thanks, @kse-music! This is now merged into `main`.