Add Support GenerateOneTimeTokenRequestResolver
spring-projects/spring-security pull request #16297
Opened 2024-12-17 16:15 UTC by franticticktick

Closes gh-16291

2025-01-21 16:56 UTC, rwinch requested changes
Thanks for the PR! I've provided feedback inline.

2025-01-21 16:56 UTC, rwinch commented on core/src/main/java/org/springframework/security/authentication/ott/GenerateOneTimeTokenRequest.java
> +	public GenerateOneTimeTokenRequest(String username, int expiresIn) {
Please change expiresIn to a Duration

2025-01-21 16:56 UTC, rwinch commented on web/src/main/java/org/springframework/security/web/authentication/ott/DefaultGenerateOneTimeTokenRequestResolver.java
> +	private static final int DEFAULT_EXPIRES_IN = 300;
Please change this to a Duration

2025-01-21 16:56 UTC, rwinch commented on web/src/main/java/org/springframework/security/web/authentication/ott/DefaultGenerateOneTimeTokenRequestResolver.java
> +	private int expiresIn = DEFAULT_EXPIRES_IN;
Please change this to a Duration

2025-01-21 16:56 UTC, rwinch commented on web/src/main/java/org/springframework/security/web/authentication/ott/DefaultGenerateOneTimeTokenRequestResolver.java
> +	public void setExpiresIn(int expiresIn) {
Please change this to a Duration

2025-01-21 16:56 UTC, rwinch commented on config/src/test/java/org/springframework/security/config/annotation/web/configurers/ott/OneTimeTokenLoginConfigurerTests.java
> +	void oneTimeTokenWhenCustomTokenExpirationTimeSetThenAuthenticate() throws Exception {
Please add tests to the Kotlin DSL as well.

2025-01-21 16:56 UTC, rwinch commented on core/src/main/java/org/springframework/security/authentication/ott/GenerateOneTimeTokenRequest.java
> +	private static final int DEFAULT_EXPIRES_IN = 300;
Please change this to a Duration

2025-01-21 16:56 UTC, rwinch commented on core/src/main/java/org/springframework/security/authentication/ott/GenerateOneTimeTokenRequest.java
> +	private final int expiresIn;
Please change this to a Duration

2025-01-21 16:56 UTC, rwinch commented on core/src/main/java/org/springframework/security/authentication/ott/GenerateOneTimeTokenRequest.java
> +	public int getExpiresIn() {
Please change this to a Duration

2025-01-21 16:56 UTC, rwinch commented on core/src/main/java/org/springframework/security/authentication/ott/GenerateOneTimeTokenRequest.java
> +		this.expiresIn = DEFAULT_EXPIRES_IN;
```suggestion
		this(username, DEFAULT_EXPIRES_IN);
```

Delegating to the other constructor ensures we don't have to keep the validation in two places

2025-01-21 20:50 UTC, franticticktick commented
@rwinch thanks for feedback, all your comments have been resolved.

2025-01-21 22:07 UTC, rwinch requested changes
I'm sorry I missed one more thing. Can you please document the changes and ensure to add a link in the What's New section to those changes?

2025-01-22 12:58 UTC, franticticktick commented
Added documentation, @rwinch done :)

2025-01-22 23:09 UTC, rwinch approved these changes

2025-01-22 23:09 UTC, merged

2025-01-22 23:11 UTC, rwinch commented
Thanks for the PR and your quick attention to changes! This is now merged into main 😄