Remove Deprecated Usages of RemoteJWKSet
spring-projects/spring-security pull request #16296
Opened 2024-12-17 05:41 UTC by kwondh5217

close gh-16251

2025-01-16 23:26 UTC, jzheaux requested changes
Thanks, @kwondh5217, for the PR! I've left some feedback inline.

2025-01-16 23:26 UTC, jzheaux commented on oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java
> +			private final URLBasedJWKSetSource urlBasedJWKSetSource;
Since we are doing our own implementation of `JWKSource`, it should be possible to use `RestOperations` and `Cache` directly instead of implementing additional Nimbus interfaces.

2025-01-16 23:26 UTC, jzheaux commented on oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java
> +			if(this.cache == null) {
Let's update this so that the member variable is set to `NoOpCache`. In this way, the null checking here and downstream is unnecessary.

2025-01-17 05:49 UTC, kwondh5217 commented on oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java
> +			private final URLBasedJWKSetSource urlBasedJWKSetSource;
Hi @jzheaux, I have a couple of questions regarding the feedback:

1. Regarding "Since we are doing our own implementation of `JWKSource`, it should be possible to use `RestOperations` and `Cache` directly instead of implementing additional Nimbus interfaces":

   Does this mean we should replace the custom `SpringJWKSetCache` implementation with direct usage of Spring's `Cache`?

2. I am also considering whether to streamline the code by either:
   - Using `RestOperations` directly, or
   - Using `RestOperationsResourceRetriever`

Below are the two possible approaches:

- **Direct `RestOperations`**:
    ```java
    private static final class SpringURLBasedJWKSource<C extends SecurityContext> implements JWKSource<C> {

        private final RestOperations restOperations;

        // Implementation logic uses restOperations directly
    }
    ```

- **Using `ResourceRetriever`**:
    ```java
    private static final class SpringURLBasedJWKSource<C extends SecurityContext> implements JWKSource<C> {

        private final ResourceRetriever resourceRetriever;

        // Implementation logic continues to leverage resourceRetriever
    }
    ```

Would it be better to reuse the already implemented `RestOperationsResourceRetriever`, or to use `RestOperations` directly within the class? 

If we go with the direct `RestOperations` approach, should the `RestOperationsResourceRetriever` implementation be removed entirely? 

Thank you for your feedback!

2025-01-17 07:09 UTC, holzerch commented on oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java
> +						synchronized (this) {
Could you please replace this `synchronized` statement with an `ReentrantLock`. Otherwise this could cause thread pinning with virtual threads.

2025-01-17 16:03 UTC, kwondh5217 commented on oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java
> +						synchronized (this) {
@holzerch Thank you for the feedback! 
I’ll replace the synchronized block with a ReentrantLock as suggested.

2025-01-27 17:34 UTC, jzheaux commented on oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java
> +			private final URLBasedJWKSetSource urlBasedJWKSetSource;
Yes, `RestOperationsResourceRetriever` and `SpringJWKSetCache` would both be removed entirely.

2025-02-04 17:42 UTC, closed without merging

2025-02-18 16:44 UTC, jzheaux commented
Superceded by https://github.com/spring-projects/spring-security/pull/16537