getRemoteUser() returns name of object implementing AuthenticatedPrinciple
spring-projects/spring-security pull request #9102
Opened 2020-10-07 13:16 UTC by sjrd218

Returns the name of the authenticated principle instead of falling through to the toString() method which may render a string representation of the entire object rather than a username.

This behavior is helpful in OAuth2 and Saml2 configurations.

Fixes: #3357

2020-10-07 13:16 UTC, pivotal-issuemaster commented
@sjrd218 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=9102)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=9102) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2020-10-07 13:18 UTC, pivotal-issuemaster commented
@sjrd218 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=9102)!

2020-11-13 21:24 UTC, jzheaux requested changes
Thanks for the PR, @sjrd218! I've left some feedback inline.

Also would you please format your commit to follow [the contribution guidelines](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.adoc#format-commit-messages)? Thanks!

2020-11-17 15:51 UTC, sjrd218 commented
@jzheaux Having trouble running gradle tasks for this project now.

Constantly seeing:
```A problem occurred configuring root project 'spring-security'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not download jackson-module-parameter-names-2.11.1.jar (com.fasterxml.jackson.module:jackson-module-parameter-names:2.11.1)
      > Could not get resource 'https://repo.spring.io/plugins-snapshot/com/fasterxml/jackson/module/jackson-module-parameter-names/2.11.1/jackson-module-parameter-names-2.11.1.jar'.
         > Could not GET 'https://repo.spring.io/plugins-snapshot/com/fasterxml/jackson/module/jackson-module-parameter-names/2.11.1/jackson-module-parameter-names-2.11.1.jar'. Received status code 401 from server: Unauthorized
```

2020-11-17 18:34 UTC, jzheaux commented
Thanks, @sjrd218, will you please rebase and try again? There were some changes made yesterday to address that issue.

2020-11-20 19:52 UTC, closed without merging