make SP NameIDPolicy configurable in RelyingPartyRegistration
spring-projects/spring-security pull request #9227
Opened 2020-12-01 15:55 UTC by amergey

closes gh-9115

2020-12-01 21:38 UTC, jzheaux commented
Thanks for the PR, @amergey! This PR seems broader than the scope of #9115, so I think we first should take a step back and make sure that we're on the same page about what support should go into the framework and where.

To start that, will you please add some detail to #9115 about your use case?

2020-12-09 19:36 UTC, amergey commented
I have updated #9115, I am not the reporter so, I add a comment, I cannot edit the issue.

2021-11-05 19:50 UTC, jzheaux requested changes
@amergey, thanks for your patience on this review. I've left some feedback inline.

Would you please update the copyright year on any edited files and also squash your commits?

We can schedule this for 5.7.0-M1.

2021-11-05 19:50 UTC, jzheaux commented on saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistration.java
> +	private final String nameIDFormat;
For consistency, will you please lowercase acronyms like so: `nameIdFormat`. Please do the same for the associated getter and setter.

2021-11-05 19:50 UTC, jzheaux commented on saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistration.java
> +	 * @since 5.5
Please update `@since` flags to 5.7

2021-11-22 19:49 UTC, amergey commented
I tried to made requested changes, but this PR is quite old already and I have trouble to rebase it to main, it would have been better to make these suggestions last year ....

2021-12-01 20:28 UTC, jzheaux commented
>  it would have been better to make these suggestions last year ....

I'm sorry it took so long to get back to this. I corrected the rebase and this is now merged via `a17dfb8456cf3a517d44cfcccdaa7a1d2ae6121f` for 6.0 and `dbe4d704f844d7d3a4b7048e004c07e1496033d2` for 5.7.

2021-12-01 20:28 UTC, closed without merging