LdapAuthoritiesPopulator should be postProcessed
spring-projects/spring-security pull request #9276
Opened 2020-12-10 18:55 UTC by fhanik

Currently we can set an `LdapAuthoritiesPopulator` and override the default one. However, the current implementation doesn't allow us to create a delegate to the default populator, because it isn't post processed

This simple fix will allow an easier customization of the `LdapAuthoritiesPopulator`

2020-12-10 18:58 UTC, fhanik commented
Note: I ran into this [issue creating](https://github.com/spring-projects/spring-security/issues/9275) this PR and used a temporary work around for my local build

https://github.com/spring-projects/spring-security/issues/9275

2020-12-11 16:29 UTC, jzheaux requested changes
Thanks for the PR, @fhanik! Will you please update the copyright on these classes so that the end date is `2020`?

There is a checkstyle error in the build. I realize that locally you might not have gotten that given the `401` issue you were experiencing earlier in the build, but I think if you try again, you'll see that error now.

2021-02-05 20:28 UTC, jzheaux commented
@fhanik, are you able to make the requested changes?

2021-11-19 19:24 UTC, jzheaux commented
Thanks, @fhanik this is now merged via ae0860801146b860586280594d7fc6431b766b18. I also added a polish to simplify the test, change the copyright date, and address the checkstyle errors.

2021-11-19 19:24 UTC, closed without merging