feat() : make max-session configurable
spring-projects/spring-security pull request #9280
Opened 2020-12-14 17:47 UTC by mazenaissa

set max-session to token type and resolve placeholder

Closes gh-9202

2020-12-16 19:06 UTC, jzheaux requested changes
Thanks, @mazenaissa for the PR! I've left some feedback inline.

2020-12-16 19:06 UTC, jzheaux commented on config/src/main/java/org/springframework/security/config/http/HttpConfigurationBuilder.java
> +			String maxSessions = this.pc.getReaderContext().getEnvironment()
Would you please add a test similar to [this one](https://github.com/spring-projects/spring-security/blob/2abf59b695b3ad14719299ed17ff47b181eed802/config/src/test/java/org/springframework/security/config/http/SessionManagementConfigTests.java#L348) in order to demonstrate that the placeholder works?

Tests like [this one](https://github.com/spring-projects/spring-security/blob/2abf59b695b3ad14719299ed17ff47b181eed802/config/src/test/java/org/springframework/security/config/http/PlaceHolderAndELConfigTests.java#L55) may prove useful for getting the property set.

2021-01-05 20:37 UTC, jzheaux requested changes
Thanks, @mazenaissa for the changes! Sorry for the delay in responding as I've been out for the holidays. 

I've left just a bit more feedback inline. Also, in preparation for merging, would you please squash your commits? In the resulting single commit, please make sure to include the phrase `Closes gh-9202` like so:

```
Make max-session configurable

Closes gh-9202
```

2021-01-05 20:37 UTC, jzheaux commented on config/src/test/java/org/springframework/security/config/http/SessionManagementConfigTests.java
> -/*
Will you please double-check the diff on this file? Git thinks that you've changed the entire file when I think you only intended to add tests.

2021-01-05 20:37 UTC, jzheaux commented on config/src/test/java/org/springframework/security/config/http/SessionManagementConfigTests.java
> -/*
Also, please make sure that the copyright year is updated.

2021-01-05 20:37 UTC, jzheaux commented on config/src/test/resources/org/springframework/security/config/http/SessionManagementConfigTests-ConcurrencyControlMaxSessionsPlaceHolder.xml
> +		<b:bean name="basicController"
Will you please double-check the whitespace here? It looks like it needs to be outdented.

2021-01-05 20:46 UTC, closed without merging

2021-01-05 20:54 UTC, jzheaux commented
@mazenaissa I think this is a good feature that you were adding - do you no longer need it?

If you do still need the feature, but there's a part you feel you cannot do, I'd be happy to help you get things ready for merging, just let me know.

2021-01-05 20:58 UTC, mazenaissa commented
Yes, I will make the changes ASAP.
Thanks,

2021-01-05 21:49 UTC, mazenaissa commented
Hello @jzheaux 
All changes are in this PR #9328 
Thanks,