Add setMetadataFilename method to Saml2MetadataFilter
spring-projects/spring-security pull request #9393
Opened 2021-02-01 15:22 UTC by GitHanter

Add setMetadataFilename method to Saml2MetadataFilter

Populated shared objects RelyingPartyRegistrationRepository and DefaultRelyingPartyRegistrationResolver

Closes gh-9317

2021-02-02 23:04 UTC, jzheaux requested changes
Thanks, @GitHanter, for the PR! I've left my feedback inline.

2021-02-02 23:04 UTC, jzheaux commented on samples/boot/saml2login/src/main/java/sample/SecurityConfig.java
> +				new SecurityConfigurerAdapter<DefaultSecurityFilterChain, HttpSecurity>() {
Let's simplify this to:

```java
@Bean 
Saml2MetadataFilter metadataFilter(RelyingPartyRegistrationRepository registrations) {
    DefaultRelyingPartyRegistrationResolver resolver = new DefaultRelyingPartyRegistrationResolver(registrations);
    return new Saml2MetadataFilter(resolver, new OpenSamlMetadataResolver());
}
```

I think the filter chain configuration can be removed at that point.

Also, in the sample, let's leave out the custom filename. The reason is that we want the samples to be a very simple introduction to Spring Security.

2021-02-03 12:29 UTC, GitHanter commented
@jzheaux 

Really appreciate your detail review, I'll resolve the issues you point out and force push two commits :

- one with `setMetadataFilename` method change
- another with HTTP header` Content-Disposition` encoding changes

2021-02-18 17:00 UTC, jzheaux commented
@GitHanter are you able to make the requested changes? I'm happy to help make them if you are busy.

2021-02-19 01:43 UTC, GitHanter commented
@jzheaux Sorry for the delay.

I was on my Spring Festival vacation last week, I'll do it this weekend CST.

2021-02-23 18:03 UTC, jzheaux commented on saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/Saml2MetadataFilterTests.java
> +	@Test
Can you add a test that shows that when the metadata filename is set, then it's used when the filter is invoked?

2021-02-23 18:04 UTC, jzheaux commented on saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/Saml2MetadataFilter.java
>  package org.springframework.security.saml2.provider.service.web;
In any files you change, will you please make sure that the copyright is updated to the current year?

2021-03-02 15:26 UTC, jzheaux commented
@GitHanter, thanks again for the PR! This is now merged into `master`. Also, I added a polish commit of 3e8ad4bc2bbbfef80180f95c803b32e5082f584e to simplify the test a bit.

2021-03-02 15:26 UTC, closed without merging