Add RememberMeDsl
spring-projects/spring-security pull request #9411
Opened 2021-02-06 00:22 UTC by IvanPavlov1995

Issue: gh-9319

2021-02-10 12:04 UTC, eleftherias requested changes
Thanks for the PR @IvanPavlov1995! 
I left some comments inline.

2021-02-20 12:57 UTC, IvanPavlov1995 commented on config/src/main/kotlin/org/springframework/security/config/web/servlet/RememberMeDsl.kt
> +    var rememberMeParameter: String = DEFAULT_REMEMBER_ME_NAME
Done

2021-02-20 12:58 UTC, IvanPavlov1995 commented on config/src/test/kotlin/org/springframework/security/config/web/servlet/RememberMeDslTest.kt
> +/*
Thanks for pointing that, fixed

2021-02-20 13:10 UTC, IvanPavlov1995 commented on config/src/main/kotlin/org/springframework/security/config/web/servlet/RememberMeDsl.kt
> +            rememberMe.rememberMeParameter(rememberMeParameter)
Done.
I have a question regarding `also` syntax. Is there a reason not to use function reference in such configurations? I mean following is shorter and with that I don't have to use `!!` operator:
```kotlin
useSecureCookie?.also(rememberMe::useSecureCookie)
```

2021-02-22 08:14 UTC, eleftherias commented on config/src/main/kotlin/org/springframework/security/config/web/servlet/RememberMeDsl.kt
> +            rememberMe.rememberMeParameter(rememberMeParameter)
There is no particular reason. We could use function references instead. I will merge this PR as is, but feel free to create an additional PR if you think it's something we should change.

2021-02-22 08:15 UTC, merged