Set 'details' on authentication token created by HttpServlet3RequestFactory
spring-projects/spring-security pull request #9597
Opened 2021-04-11 14:15 UTC by karltinawi

Currently the login mechanism when triggered by executing HttpServlet3RequestFactory#login does not set any details on the underlying authentication token that is authenticated.

This change adds support for setting an AuthenticationDetailsSource on the HttpServlet3RequestFactory, which defaults to a WebAuthenticationDetailsSource. The instance used can be overridden by the ServletApiConfigurer if a shared object of type AuthenticationDetailsSource has been registered.

Closes gh-9579

2021-04-12 10:15 UTC, karltinawi commented
This is my first contribution to this project so apologies in advance for any silly mistakes! I couldn't get the build working reliably either locally on my Windows machine so it's a bit of a trial-and-error to get these checkstyle issues resolved as I'm relying on the build currently...

2021-04-15 18:57 UTC, jzheaux requested changes
Thanks for the PR, @karltinawi! I've left my feedback inline.

2021-04-15 18:57 UTC, jzheaux commented on web/src/main/java/org/springframework/security/web/servletapi/HttpServlet3RequestFactory.java
> +import org.springframework.security.authentication.AuthenticationDetailsSource;
Will you please update the copyright message to `2021` for classes that you modify?

2021-04-15 18:57 UTC, jzheaux commented on web/src/main/java/org/springframework/security/web/servletapi/SecurityContextHolderAwareRequestFilter.java
> +import org.springframework.security.authentication.AuthenticationDetailsSource;
Will you please add a test to `SecurityContextHolderAwareRequestFilterTests` that demonstrates the `AuthenticationDetailsSource` is being used?

2021-05-03 18:44 UTC, jzheaux commented
Hi, @karltinawi, are you able to update the PR?

2021-05-03 18:57 UTC, karltinawi commented
Hey. Yes sorry have been really busy. Will try get it done this week.

2021-06-28 22:14 UTC, jzheaux commented
Hi, @karltinawi. Are you able to apply the requested changes?

2021-11-22 16:48 UTC, marcusdacoregio commented
Hi @karltinawi, any updates on the requested changes?

2021-12-02 23:28 UTC, sjohnr commented
Thanks for the PR, @karltinawi. This is now in main as c57fc309c245de8171e67be1ef1ebb6c5b6b0d4c. I went ahead and added a polish commit for the remaining items including removing the changes to the configurer and filter for now: d37ff18b694844ab36c678b7a6440933291639dc. Let me know if you have any questions.

2021-12-02 23:28 UTC, closed without merging