Make Csrf cookie secure flag configurable (WebFlux)
spring-projects/spring-security pull request #9679
Opened 2021-04-25 13:20 UTC by ThomasVitale

Make the XSRF-TOKEN cookie secure flag configurable in CookieServerCsrfTokenRepository.

Closes gh-9678

2021-04-26 09:41 UTC, eleftherias requested changes
Thanks for the PR @ThomasVitale!
I've left a couple of comments.

2021-04-26 09:41 UTC, eleftherias commented on web/src/main/java/org/springframework/security/web/server/csrf/CookieServerCsrfTokenRepository.java
> + * Copyright 2002-2020 the original author or authors.
2021 :)

2021-04-26 09:41 UTC, eleftherias commented on web/src/main/java/org/springframework/security/web/server/csrf/CookieServerCsrfTokenRepository.java
> +	public void setSecure(boolean secure) {
Please add `@since 5.5`

2021-04-26 16:14 UTC, ThomasVitale commented on web/src/main/java/org/springframework/security/web/server/csrf/CookieServerCsrfTokenRepository.java
> + * Copyright 2002-2020 the original author or authors.
That's awkward :) I fixed it.

2021-04-26 16:14 UTC, ThomasVitale commented on web/src/main/java/org/springframework/security/web/server/csrf/CookieServerCsrfTokenRepository.java
> +	public void setSecure(boolean secure) {
Done

2021-04-26 16:30 UTC, ThomasVitale commented
@eleftherias thanks for reviewing the PR. I have addressed your comments and pushed an update.

2021-04-27 07:34 UTC, merged

2021-04-27 07:34 UTC, eleftherias commented
Thanks @ThomasVitale! This is now merged into main.