Properly clean cookies with context path after logout
spring-projects/spring-security pull request #9740
Opened 2021-05-12 16:02 UTC by alexey-anufriev

Closes gh-8846

2021-06-01 10:27 UTC, eleftherias requested changes
Thanks for the PR @alexey-anufriev!
I have left one comment inline.
Please also update the copyright year at the top of the file to 2021.

2021-06-01 10:27 UTC, eleftherias commented on web/src/test/java/org/springframework/security/web/authentication/logout/CookieClearingLogoutHandlerTests.java
>  			// gh-2325
Please remove this comment since the updated behaviour no longer aligns with what is mentioned in issue 2325.

2021-06-04 13:30 UTC, alexey-anufriev commented
@eleftherias, thank you for the review. I made the changes you requested.

2021-06-04 13:42 UTC, merged

2021-06-04 13:42 UTC, eleftherias commented
Thanks @alexey-anufriev! This is now merged into the main branch.