Allow Creating RelyingPartyRegistration from Metadata InputStream
spring-projects/spring-security pull request #9771
Opened 2021-05-18 17:47 UTC by marcusdacoregio

Update SAML2 Login reference documentation to reflect the changes

Closes gh-9558

2021-05-21 22:24 UTC, jzheaux requested changes
Thanks, @marcusdacoregio! And sorry for the delay, it looks like I forgot to press "submit" for my review. :/

2021-05-24 13:03 UTC, marcusdacoregio commented on saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistrationsTests.java
> +	public void fromMetadataInputStreamWhenUnresolvableThenSaml2Exception() throws Exception {
Yeah, I agree that "empty" is better for this scenario

2021-05-24 13:25 UTC, marcusdacoregio commented
> 
> 
> Thanks, @marcusdacoregio! And sorry for the delay, it looks like I forgot to press "submit" for my review. :/

Thanks @jzheaux, I've submitted a new version with your suggestions, would you please review again?

2021-06-29 18:50 UTC, jzheaux approved these changes

2021-06-30 11:02 UTC, merged