Add Spanish translation
spring-projects/spring-security pull request #9822
Opened 2021-05-27 08:21 UTC by rubensa

Fix https://github.com/spring-projects/spring-security/issues/9315 for Spanish

2021-05-27 08:21 UTC, pivotal-cla commented
@rubensa Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=9822)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=9822) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-05-27 09:26 UTC, pivotal-cla commented
@rubensa Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=9822)!

2021-06-01 18:12 UTC, sjohnr requested changes
Hi @rubensa. Thanks for this submission! Please see my feedback inline.

Also, will you please squash your commits and format the resulting commit like so:

```
Commit Title

Closes gh-9315
```

2021-06-01 18:12 UTC, sjohnr commented on web/src/main/resources/org/springframework/security/web/messages_es.properties
> +ExceptionTranslationFilter.insufficientAuthentication=Para acceder a este recurso se requiere autenticaci\u00f3n completa
Please also add this translation to `core/src/main/resources/org/springframework/security/messages_es_ES.properties`.

2021-06-15 10:12 UTC, rubensa commented
@sjohnr Done!  Sorry for the delay.

2021-06-15 10:33 UTC, rubensa commented
@sjohnr Just realized that `PersistentTokenBasedRememberMeServices.cookieStolen` in `core/src/main/resources/org/springframework/security/messages_es_ES.properties` was in English so I translated it too.

2021-06-15 14:11 UTC, merged