Support for X509 Certificate in RsaKeyConverters #9736
spring-projects/spring-security pull request #9853
Opened 2021-06-02 12:57 UTC by shazin

Support for X509 Certificate in RsaKeyConverters

2021-06-28 22:48 UTC, jzheaux requested changes
Thanks, @shazin! I've left some feedback inline.

2021-06-28 22:48 UTC, jzheaux commented on core/src/main/java/org/springframework/security/converter/RsaKeyConverters.java
> +					publicKey = (RSAPublicKey) keyFactory.generatePublic(new X509EncodedKeySpec(x509));
Please change this to return the public key as this is more typical of Spring Security code. Subsequently, please also change the `else if` below to an `if`.

2021-06-28 22:48 UTC, jzheaux commented on core/src/main/java/org/springframework/security/converter/RsaKeyConverters.java
> +					"Key is not in PEM-encoded X.509 format or a valid X.509 certificate, please check that the header begins with -----"
Even though there were dashes in the output originally, I don't think the dashes are necessary since they are included in the constants.

2021-06-28 22:48 UTC, jzheaux commented on core/src/main/java/org/springframework/security/converter/RsaKeyConverters.java
> +				finally {
Instead of `finally`, please use a try-with-resources construct.

2021-06-28 22:48 UTC, jzheaux commented on core/src/main/java/org/springframework/security/converter/RsaKeyConverters.java
> +					publicKey = (RSAPublicKey) certificate.getPublicKey();
Please change this to return the public key as this is more typical of Spring Security code.

2021-06-28 22:48 UTC, jzheaux commented on core/src/main/java/org/springframework/security/converter/RsaKeyConverters.java
> +					CertificateFactory certificateFactory = CertificateFactory.getInstance(X509_CERTIFICATE);
Please generate the `CertificateFactory` outside of the function, as is done with `rsaFactory()`.

2021-06-28 22:48 UTC, jzheaux commented on core/src/main/java/org/springframework/security/converter/RsaKeyConverters.java
> +	public static final String X509_CERTIFICATE = "X.509";
I think this string should be inlined so that it remains consistent with existing code.

2021-06-28 22:48 UTC, jzheaux commented on core/src/main/java/org/springframework/security/converter/RsaKeyConverters.java
> +	 * X.509 Certificate file into a {@link RSAPublicKey}.
Please leave the word "file" out since it doesn't have to be a file.

2021-06-28 22:48 UTC, jzheaux commented on core/src/main/java/org/springframework/security/converter/RsaKeyConverters.java
>  import java.io.BufferedReader;
Will you please update the copyright to `2021` in any files that you change?

2021-07-01 18:35 UTC, shazin commented
@jzheaux Thanks for the review comments. Those are addressed and PR is updated.

2021-07-01 19:53 UTC, jzheaux commented
Thanks, @shazin! For some reason, the PR includes several unrelated commits. Will you please rebase and force push your PR?

2021-07-02 03:25 UTC, shazin commented
> Thanks, @shazin! For some reason, the PR includes several unrelated commits. Will you please rebase and force push your PR?

@jzheaux Rebased and pushed only the commits to PR.

2021-07-06 20:09 UTC, jzheaux requested changes
Thanks, @shazin! In preparation for merging, will you please squash your commits and change your final commit message to something like the following:

```bash
Add X.509 Certificate Support

Closes gh-9736
```

When the commit uses the word "closes" this alerts GitHub to close the ticket once this PR is merged.

2021-07-08 07:24 UTC, shazin commented
> Thanks, @shazin! In preparation for merging, will you please squash your commits and change your final commit message to something like the following:
> 
> ```shell
> Add X.509 Certificate Support
> 
> Closes gh-9736
> ```
> 
> When the commit uses the word "closes" this alerts GitHub to close the ticket once this PR is merged.

Done. Thanks for the review.

2021-07-12 20:21 UTC, jzheaux approved these changes

2021-07-12 20:21 UTC, merged

2021-07-12 20:25 UTC, jzheaux commented
Thanks, @shazin! This is now merged into `main` in 5f7d8712583526a781af8142a54146d964ca8fdb. 

I also added a polish that errors instead of returning `null` and only skips the header for the given format in 01af7877ea7390ea93d614b5f8394f460cb09b13.