Added support for the CAS gateway feature.
spring-projects/spring-security pull request #9881
Opened 2021-06-08 13:10 UTC by yvangg

This is the CAS gateway feature.
This is a implementation is based on the following discussion (PR): https://github.com/spring-projects/spring-security/pull/40#

I did some modifications in order to perform the CAS gateway redirection only if the CAS cookie is present on the client application request. Of course this will not fit in all situations (where CAS domain is differente from client applications won't work), but for many of situations this is a pretty good approach.

Regards.

2021-06-08 13:10 UTC, pivotal-cla commented
@yvangg Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=9881)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=9881) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-06-08 13:11 UTC, pivotal-cla commented
@yvangg Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=9881)!

2021-08-16 15:08 UTC, yvangg commented
Do we have any news about this? Why is not being merged?

2021-11-17 11:58 UTC, marcusdacoregio commented
Hi @yvangg.

The CAS module has been removed in Spring Security 6.0. See https://github.com/spring-projects/spring-security/issues/10441.

So, for now, we have to wait to see if the java-cas-client is going to support Jakarta EE 9.

2021-11-17 12:18 UTC, yvangg commented
Hi, @marcusdacoregio I understand that you have removed that in Spring Security 6.0, but, Why don't you accept this request on the 5.5.x branch?

Our applications are using spring-security 5.5.x and we do not have in mind update to 6.0 soon.

It will be helpfull have support for the CAS gateway feature.

2021-11-17 15:45 UTC, marcusdacoregio commented
Hi @yvangg. Unfortunately, we can't add new features to older branches, like `5.5.x`.

We are gonna start planning features for the `5.7` release next month, so I'll add this PR to the next milestone and we can start working on this by that time.

2022-01-21 20:16 UTC, rwinch requested changes
I've posted on here some changes. In general, I think the original PR was closer to what should be used. We just needed the Cookies to prevent making too many requests.

2022-03-25 17:40 UTC, marcusdacoregio commented
@yvangg have you had the chance to see @rwinch review and apply the suggested changes? Thanks!

2022-11-17 12:15 UTC, marcusdacoregio commented
I'll close this since we do not have more minor releases planned for 5.x and the CAS support has been removed in Spring Security 6. See #10441

2022-11-17 12:15 UTC, closed without merging

2022-11-17 12:37 UTC, Emkas commented
But there is also a ticket to re-add CAS... So why do not link to #11674. 

This is an important feature and if I remember correctly original issue about it has probably +10 years.

2022-11-18 12:35 UTC, marcusdacoregio commented
@Emkas, I've just linked this PR with #11674. When the support is re-added this can be reconsidered. Thanks for the reminder.

2022-11-18 13:51 UTC, Emkas commented
Ok, I'll subscribe #11674.

2023-03-08 17:41 UTC, marcusdacoregio commented
Hi @Emkas, I think creating a new PR targeting the `main` branch is the recommended approach here since it is a new feature. Also, the new PR should contain the changes requested by @rwinch. Is @yvangg still willing to work on this?

2023-03-08 19:27 UTC, yvangg commented
Hi @marcusdacoregio, I am willing to work on this. But probably I will need to test again the changes in the current 6.1.x branch, In addition, I did not receive any answer from @rwinch about some of my comments. I will checkout the main branch and I will test it again, if everything works as I expect I will do a new PR.

2023-07-27 18:55 UTC, SandwichCZ commented
Hi, are the are news regarding this issue? This would be a quite helpful feature to have and it seems like there is interest in implementing it. Perhaps re-opening the ticket should be considered.