Improve Error Message for Invalid Properties in InMemoryUserDetailsManager
spring-projects/spring-security pull request #9919
Opened 2021-06-15 17:10 UTC by marcusdacoregio

Check if the UserAttribute is null when instantiating the InMemoryUserDetailsManager using the Properties argument's constructor

Closes gh-3403

2021-06-28 21:03 UTC, jzheaux requested changes
Thanks, @marcusdacoregio! I've left some feedback inline.

2021-06-30 15:36 UTC, marcusdacoregio commented
Thanks for your review @jzheaux. I've updated the PR with your suggestions. Would you please review it again?

2021-06-30 16:05 UTC, jzheaux approved these changes

2021-06-30 16:07 UTC, merged

2021-06-30 16:07 UTC, jzheaux commented
Thanks, @marcusdacoregio! This is now merged into `main`.